#include "mainwindow.h"

// #include <QStatusBar>

#include "ui_mainwindow.h" // This is auto generated by CMake's AUTOUIC to the build folder from mainwindow.ui

MainWindow::MainWindow(QWidget* parent)
  : QMainWindow(parent), ui(new Ui::MainWindow) {
    ui->setupUi(this);

    // ---- STACK PAGES NAVIGATION ----
    connect(ui->btnNavDtr, &QPushButton::clicked,
            this, [this] { ui->stackPages->setCurrentWidget(ui->pageDtr); });

    connect(ui->btnBatchReport, &QPushButton::clicked,
            this, [this] { ui->stackPages->setCurrentWidget(ui->pageBatch); });
          
    connect(ui->btnAdd, &QPushButton::clicked,
            this, [this] { ui->stackPages->setCurrentWidget(ui->pageAdd); });

    connect(ui->btnSignatory, &QPushButton::clicked,
            this, [this] { ui->stackPages->setCurrentWidget(ui->pageSignatory); });

//     #ifdef NDEBUG // CMake Defines NDEBUG only in release builds
//       ui->buildLabel->setText(QStringLiteral("RELEASE build"));
//     #else
//       ui->buildLabel->setText(QStringLiteral("DEBUG build"));
//     #endif

//     connect(ui->greetButton, &QPushButton::clicked,
//             this, &MainWindow::onGreetClicked);

//     connect(ui->nameEdit, &QLineEdit::returnPressed,
//             this, &MainWindow::onGreetClicked);
// }

// MainWindow::~MainWindow() { delete ui; }

// void MainWindow::onGreetClicked() {
//   const QString name = ui->nameEdit->text().trimmed();

//   if (name.isEmpty()) {
//     ui->outputLabel->setText(QStringLiteral("Please type name in the box."));
//     statusBar()->showMessage(QStringLiteral("Empty input"), 2000);
//     return;
//   }

//   ui->outputLabel->setText(QStringLiteral("Hello, %1!").arg(name));
//   statusBar()->showMessage(QStringLiteral("Greeted %1").arg(name), 2000);
}